from __future__ import annotations

BASELINE_ENV_KEYS = [
    "MIN_TURNS",
    "MAX_TURNS",
    "STOP_CONFIDENCE",
    "CONF_SUPPORT_TAU",
    "CONF_UP_ALPHA",
    "CONF_DEPTH_WEIGHT",
    "SUPERVISOR_EVIDENCE_MIN_SCORE",
    "SUPERVISOR_EVIDENCE_RISK_THRESHOLD",
    "SUPERVISOR_ESCAPE_EMPTY_STREAK",
]

STAGE1_GRID = [
    {"MIN_TURNS": 16, "MAX_TURNS": 32, "STOP_CONFIDENCE": 0.62, "CONF_SUPPORT_TAU": 1.15, "CONF_UP_ALPHA": 0.60},
    {"MIN_TURNS": 18, "MAX_TURNS": 34, "STOP_CONFIDENCE": 0.66, "CONF_SUPPORT_TAU": 1.25, "CONF_UP_ALPHA": 0.55},
    {"MIN_TURNS": 20, "MAX_TURNS": 36, "STOP_CONFIDENCE": 0.70, "CONF_SUPPORT_TAU": 1.35, "CONF_UP_ALPHA": 0.50},
    {"MIN_TURNS": 18, "MAX_TURNS": 34, "STOP_CONFIDENCE": 0.66, "CONF_SUPPORT_TAU": 1.25, "CONF_UP_ALPHA": 0.55, "CONF_DEPTH_WEIGHT": 0.75},
]

ROUTING_GRID = [
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.26,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.20,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.30,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.34,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.26,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 3,
    },
]
