from __future__ import annotations

BASELINE_ENV_KEYS = [
    "MIN_TURNS",
    "MAX_TURNS",
    "STOP_CONFIDENCE",
    "MIN_EVIDENCE_FOR_CONF_STOP",
    "SUPERVISOR_EVIDENCE_MIN_SCORE",
    "SUPERVISOR_EVIDENCE_RISK_THRESHOLD",
    "SUPERVISOR_ESCAPE_EMPTY_STREAK",
]

STAGE1_GRID = [
    {"MIN_TURNS": 4, "MAX_TURNS": 12, "STOP_CONFIDENCE": 0.72, "MIN_EVIDENCE_FOR_CONF_STOP": 1},
    {"MIN_TURNS": 6, "MAX_TURNS": 14, "STOP_CONFIDENCE": 0.75, "MIN_EVIDENCE_FOR_CONF_STOP": 2},
    {"MIN_TURNS": 6, "MAX_TURNS": 16, "STOP_CONFIDENCE": 0.80, "MIN_EVIDENCE_FOR_CONF_STOP": 2},
    {"MIN_TURNS": 6, "MAX_TURNS": 12, "STOP_CONFIDENCE": 0.70, "MIN_EVIDENCE_FOR_CONF_STOP": 2},
]

ROUTING_GRID = [
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.26,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.20,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.30,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.34,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 2,
    },
    {
        "SUPERVISOR_EVIDENCE_MIN_SCORE": 0.26,
        "SUPERVISOR_EVIDENCE_RISK_THRESHOLD": 0.22,
        "SUPERVISOR_ESCAPE_EMPTY_STREAK": 3,
    },
]
