from __future__ import annotations

from typing import Dict, List

LEXICAL_EVIDENCE_CUES: Dict[int, List[str]] = {
    1: [
        "feel sad",
        "felt sad",
        "feeling down",
        "low mood",
        "tearful",
        "dark cloud",
        "emotionally low",
    ],
    2: [
        "hopeless",
        "no future",
        "nothing will change",
        "pointless",
        "worrying about the future",
        "no way out",
    ],
    3: [
        "failure",
        "failed",
        "not good enough",
        "falling behind",
        "playing catch-up",
        "accomplished nothing",
        "wasted the whole day",
    ],
    4: [
        "no pleasure",
        "enjoy nothing",
        "hollow",
        "nothing feels good",
        "going through the motions",
        "feel like a chore",
        "not really enjoying",
        "disconnected",
        "not really being present",
    ],
    5: ["guilty", "guilt", "blame myself", "regret", "my fault", "ashamed"],
    7: ["hate myself", "dislike myself"],
    8: [
        "beat myself up",
        "self-doubt",
        "self critical",
        "second-guessing",
        "what i've done wrong",
        "pretending to be okay",
        "facade",
    ],
    9: [
        "better off dead",
        "end it",
        "kill myself",
        "self harm",
        "hurt myself",
        "not be here",
        "disappear",
        "not wake up",
        "staying safe",
    ],
    11: ["restless", "agitated", "can't sit still"],
    12: ["withdrawing", "keeping to myself", "avoid people"],
    14: ["worthless", "burden", "useless", "not enough"],
    15: [
        "no energy",
        "drained",
        "exhausted",
        "running on empty",
        "hard to muster",
        "no motivation",
        "struggle to get started",
    ],
    16: [
        "can't sleep",
        "trouble sleeping",
        "lying awake",
        "insomnia",
        "wake up tired",
        "trouble falling asleep",
        "wake up feeling",
    ],
    18: ["no appetite", "appetite", "eating less", "eating more"],
    19: [
        "can't focus",
        "concentrate",
        "distracted",
        "brain fog",
        "mind was racing",
        "lose focus",
        "zoning out",
        "mind is always elsewhere",
    ],
    20: ["fatigue", "tired all day", "worn out", "sluggish"],
}
