from __future__ import annotations

from typing import Dict, List

LEXICAL_EVIDENCE_CUES: Dict[int, List[str]] = {
    1: [
        "feel sad",
        "felt sad",
        "feeling down",
        "low mood",
        "tearful",
        "dark cloud",
        "emotionally low",
        "flat lately",
        "numb most days",
    ],
    2: [
        "hopeless",
        "no future",
        "nothing will change",
        "pointless",
        "worrying about the future",
        "no way out",
        "can't see things getting better",
        "future feels bleak",
    ],
    3: [
        "failure",
        "failed",
        "not good enough",
        "falling behind",
        "playing catch-up",
        "accomplished nothing",
        "wasted the whole day",
    ],
    4: [
        "no pleasure",
        "enjoy nothing",
        "hollow",
        "nothing feels good",
        "going through the motions",
        "feel like a chore",
        "not really enjoying",
        "disconnected",
        "not really being present",
        "autopilot",
        "used to enjoy but now",
    ],
    5: ["guilty", "guilt", "blame myself", "regret", "my fault", "ashamed"],
    7: ["hate myself", "dislike myself"],
    8: [
        "beat myself up",
        "self-doubt",
        "self critical",
        "second-guessing",
        "what i've done wrong",
        "pretending to be okay",
        "facade",
    ],
    9: [
        "better off dead",
        "end it",
        "kill myself",
        "self harm",
        "hurt myself",
        "not be here",
        "disappear",
        "not wake up",
        "staying safe",
        "dangerously heavy",
        "better off without me",
        "wish i wasn't here",
        "wish i wasnt here",
        "don't want to wake up",
        "dont want to wake up",
    ],
    11: ["restless", "agitated", "can't sit still"],
    12: [
        "withdrawing",
        "keeping to myself",
        "avoid people",
        "pulling away",
        "ignoring messages",
        "cancel plans",
    ],
    14: ["worthless", "burden", "useless", "not enough"],
    15: [
        "no energy",
        "drained",
        "exhausted",
        "running on empty",
        "hard to muster",
        "no motivation",
        "struggle to get started",
        "heavy limbs",
        "can't get moving",
    ],
    16: [
        "can't sleep",
        "trouble sleeping",
        "lying awake",
        "insomnia",
        "wake up tired",
        "trouble falling asleep",
        "wake up feeling",
    ],
    18: ["no appetite", "appetite", "eating less", "eating more"],
    19: [
        "can't focus",
        "concentrate",
        "distracted",
        "brain fog",
        "mind was racing",
        "lose focus",
        "zoning out",
        "mind is always elsewhere",
        "foggy head",
        "can't think clearly",
    ],
    20: [
        "fatigue",
        "tired all day",
        "worn out",
        "sluggish",
        "completely drained",
        "mentally drained",
        "physically drained",
    ],
}
